apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: old-prod
  labels:
    app: backend
  name: backend-deployment
spec:
  minReadySeconds: 5
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - backend
                topologyKey: kubernetes.io/hostname
              weight: 100
      initContainers:
        - args:
            - /bin/bash
            - -c
            - php artisan config:cache && php artisan route:cache
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          image: 889957192357.dkr.ecr.eu-west-3.amazonaws.com/marmelade-backend:latest
          imagePullPolicy: Always
          name: artisan

      containers:
        - name: app
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          image: 889957192357.dkr.ecr.eu-west-3.amazonaws.com/marmelade-backend:latest
          imagePullPolicy: Always
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 15
            tcpSocket:
              port: 80
            timeoutSeconds: 30
          ports:
            - containerPort: 80
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            tcpSocket:
              port: 80
          resources:
            limits:
              cpu: 200m
              memory: 400M
            requests:
              cpu: 100m
              memory: 200M