apiVersion: v1
kind: Service
metadata:
  namespace: old-prod
  labels:
    app: backend
  name: backend

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:eu-west-3:889957192357:certificate/3f0355be-7f33-40b9-a5c8-da3ecd28cea4
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"

spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80
  type: LoadBalancer