version: '3.5'

volumes:
  mysqldata:

services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/var/www/html:cached
    depends_on:
      - db
    ports:
      - 8080:80

  db:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: backend
    ports:
      - 3307:3306

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8088:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: toto42sh
