import { createActions } from 'redux-actions';

const {
  getQuestions,
  getQuestionsFailed,
  getQuestionsSucceed,
  addQuestion,
  addQuestionFailed,
  addQuestionSucceed,
  editQuestion,
  editQuestionFailed,
  editQuestionSucceed,
  createQuestion,
  createQuestionFailed,
  createQuestionSucceed,
  updateQuestion,
  updateQuestionFailed,
  updateQuestionSucceed,
  deleteQuestion,
  deleteQuestionSucceed,
  deleteQuestionFailed,
} = createActions({
  GET_QUESTIONS: (params) => ({params}),
  GET_QUESTIONS_FAILED: error => ({ error }),
  GET_QUESTIONS_SUCCEED: questions => ({ questions }),
  ADD_QUESTION: (params) => ({params}),
  ADD_QUESTION_FAILED: error => ({ error }),
  ADD_QUESTION_SUCCEED: question => ({ question }),
  EDIT_QUESTION: (id) => ({id}),
  EDIT_QUESTION_FAILED: error => ({ error }),
  EDIT_QUESTION_SUCCEED: question => ({ question }),
  CREATE_QUESTION: () => ({}),
  CREATE_QUESTION_FAILED: error => ({ error }),
  CREATE_QUESTION_SUCCEED: question => ({ question }),
  UPDATE_QUESTION: (id, params) => ({id: id, params: params}),
  UPDATE_QUESTION_FAILED: error => ({ error }),
  UPDATE_QUESTION_SUCCEED: id => ({ id }),
  DELETE_QUESTION: (id) => ({id}),
  DELETE_QUESTION_SUCCEED: (id) => ({id}),
  DELETE_QUESTION_FAILED: (error) => ({error}),
});

export {
  getQuestions,
  getQuestionsFailed,
  getQuestionsSucceed,
  addQuestion,
  addQuestionFailed,
  addQuestionSucceed,
  editQuestion,
  editQuestionFailed,
  editQuestionSucceed,
  createQuestion,
  createQuestionFailed,
  createQuestionSucceed,
  updateQuestion,
  updateQuestionFailed,
  updateQuestionSucceed,
  deleteQuestion,
  deleteQuestionSucceed,
  deleteQuestionFailed,
};
