import { createActions } from 'redux-actions';

const {
  getCategories,
  getCategoriesFailed,
  getCategoriesSucceed,
  addCategory,
  addCategoryFailed,
  addCategorySucceed,
  editCategory,
  editCategoryFailed,
  editCategorySucceed,
  createCategory,
  createCategoryFailed,
  createCategorySucceed,
  updateCategory,
  updateCategoryFailed,
  updateCategorySucceed,
  deleteCategory,
  deleteCategorySucceed,
  deleteCategoryFailed,
} = createActions({
  GET_CATEGORIES: (params) => ({params}),
  GET_CATEGORIES_FAILED: error => ({ error }),
  GET_CATEGORIES_SUCCEED: categories => ({ categories }),
  ADD_CATEGORY: (params) => ({params}),
  ADD_CATEGORY_FAILED: error => ({ error }),
  ADD_CATEGORY_SUCCEED: category => ({ category }),
  EDIT_CATEGORY: (id) => ({id}),
  EDIT_CATEGORY_FAILED: error => ({ error }),
  EDIT_CATEGORY_SUCCEED: category => ({ category }),
  CREATE_CATEGORY: () => ({}),
  CREATE_CATEGORY_FAILED: error => ({ error }),
  CREATE_CATEGORY_SUCCEED: category => ({ category }),
  UPDATE_CATEGORY: (id, params) => ({id: id, params: params}),
  UPDATE_CATEGORY_FAILED: error => ({ error }),
  UPDATE_CATEGORY_SUCCEED: id => ({ id }),
  DELETE_CATEGORY: (id) => ({id}),
  DELETE_CATEGORY_SUCCEED: (id) => ({id}),
  DELETE_CATEGORY_FAILED: (error) => ({error}),
});

export {
  getCategories,
  getCategoriesFailed,
  getCategoriesSucceed,
  addCategory,
  addCategoryFailed,
  addCategorySucceed,
  editCategory,
  editCategoryFailed,
  editCategorySucceed,
  createCategory,
  createCategoryFailed,
  createCategorySucceed,
  updateCategory,
  updateCategoryFailed,
  updateCategorySucceed,
  deleteCategory,
  deleteCategorySucceed,
  deleteCategoryFailed,
};
