apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-deployment
  namespace: prod
spec:
  maxReplicas: 20
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  targetCPUUtilizationPercentage: 50