import { createActions } from 'redux-actions';

const {
  getFeatureds,
  getFeaturedsFailed,
  getFeaturedsSucceed,
  addFeatured,
  addFeaturedFailed,
  addFeaturedSucceed,
  editFeatured,
  editFeaturedFailed,
  editFeaturedSucceed,
  createFeatured,
  createFeaturedFailed,
  createFeaturedSucceed,
  updateFeatured,
  updateFeaturedFailed,
  updateFeaturedSucceed,
  deleteFeatured,
  deleteFeaturedSucceed,
  deleteFeaturedFailed,
} = createActions({
  GET_FEATUREDS: (params) => ({params}),
  GET_FEATUREDS_FAILED: error => ({ error }),
  GET_FEATUREDS_SUCCEED: featureds => ({ featureds }),
  ADD_FEATURED: (params) => ({params}),
  ADD_FEATURED_FAILED: error => ({ error }),
  ADD_FEATURED_SUCCEED: featured => ({ featured }),
  EDIT_FEATURED: (id) => ({id}),
  EDIT_FEATURED_FAILED: error => ({ error }),
  EDIT_FEATURED_SUCCEED: featured => ({ featured }),
  CREATE_FEATURED: () => ({}),
  CREATE_FEATURED_FAILED: error => ({ error }),
  CREATE_FEATURED_SUCCEED: featured => ({ featured }),
  UPDATE_FEATURED: (id, params) => ({id: id, params: params}),
  UPDATE_FEATURED_FAILED: error => ({ error }),
  UPDATE_FEATURED_SUCCEED: id => ({ id }),
  DELETE_FEATURED: (id) => ({id}),
  DELETE_FEATURED_SUCCEED: (id) => ({id}),
  DELETE_FEATURED_FAILED: (error) => ({error}),
});

export {
  getFeatureds,
  getFeaturedsFailed,
  getFeaturedsSucceed,
  addFeatured,
  addFeaturedFailed,
  addFeaturedSucceed,
  editFeatured,
  editFeaturedFailed,
  editFeaturedSucceed,
  createFeatured,
  createFeaturedFailed,
  createFeaturedSucceed,
  updateFeatured,
  updateFeaturedFailed,
  updateFeaturedSucceed,
  deleteFeatured,
  deleteFeaturedSucceed,
  deleteFeaturedFailed,
};
