import { createActions } from 'redux-actions';

const {
  getShopQuizzes,
  getShopQuizzesFailed,
  getShopQuizzesSucceed,
  createShopQuizz,
  createShopQuizzFailed,
  createShopQuizzSucceed,
  addShopQuizz,
  addShopQuizzFailed,
  addShopQuizzSucceed,
  showShopQuizz,
  showShopQuizzFailed,
  showShopQuizzSucceed,
  editShopQuizz,
  editShopQuizzFailed,
  editShopQuizzSucceed,
  updateShopQuizz,
  updateShopQuizzFailed,
  updateShopQuizzSucceed,
  updateImage,
  updateImageFailed,
  updateImageSucceed,
} = createActions({
  GET_SHOP_QUIZZES: (params) => ({params}),
  GET_SHOP_QUIZZES_FAILED: error => ({ error }),
  GET_SHOP_QUIZZES_SUCCEED: shopQuizzes => ({ shopQuizzes }),
  CREATE_SHOP_QUIZZ: () => ({}),
  CREATE_SHOP_QUIZZ_FAILED: error => ({ error }),
  CREATE_SHOP_QUIZZ_SUCCEED: shopQuizz => ({ shopQuizz }),
  ADD_SHOP_QUIZZ: (params) => ({params}),
  ADD_SHOP_QUIZZ_FAILED: error => ({ error }),
  ADD_SHOP_QUIZZ_SUCCEED: shopQuizz => ({ shopQuizz }),
  SHOW_SHOP_QUIZZ: (id) => ({id}),
  SHOW_SHOP_QUIZZ_FAILED: error => ({ error }),
  SHOW_SHOP_QUIZZ_SUCCEED: shopQuizz => ({ shopQuizz }),
  EDIT_SHOP_QUIZZ: (id) => ({id}),
  EDIT_SHOP_QUIZZ_FAILED: error => ({ error }),
  EDIT_SHOP_QUIZZ_SUCCEED: shopQuizz => ({ shopQuizz }),
  UPDATE_SHOP_QUIZZ: (id, params) => ({id: id, params: params}),
  UPDATE_SHOP_QUIZZ_FAILED: error => ({ error }),
  UPDATE_SHOP_QUIZZ_SUCCEED: shopQuizz => ({ shopQuizz }),
  UPDATE_IMAGE: (id, params) => ({id: id, params: params}),
  UPDATE_IMAGE_FAILED: error => ({ error }),
  UPDATE_IMAGE_SUCCEED: status => ({ status }),
});

export {
  getShopQuizzes,
  getShopQuizzesFailed,
  getShopQuizzesSucceed,
  createShopQuizz,
  createShopQuizzFailed,
  createShopQuizzSucceed,
  addShopQuizz,
  addShopQuizzFailed,
  addShopQuizzSucceed,
  showShopQuizz,
  showShopQuizzFailed,
  showShopQuizzSucceed,
  editShopQuizz,
  editShopQuizzFailed,
  editShopQuizzSucceed,
  updateShopQuizz,
  updateShopQuizzFailed,
  updateShopQuizzSucceed,
  updateImage,
  updateImageFailed,
  updateImageSucceed,
};
