apiVersion: v1
kind: ConfigMap
metadata:
  namespace: preprod
  labels:
    app: backend
  name: backend-config

data:
  APP_NAME: "MRMLD BO"
  APP_ENV: "production"
  APP_DEBUG: "false"
  APP_URL: "https://preprod.mrmld.net"

  LOG_CHANNEL: "prod"
  BROADCAST_DRIVER: "log"
  CACHE_DRIVER: "file"
  MAIL_DRIVER: "ses"
  SESSION_DRIVER: "file"
  SESSION_LIFETIME: "120"
  QUEUE_DRIVER: "sync"
  FILESYSTEM_DRIVER: "s3"

  DB_CONNECTION: "mysql"
  DB_PORT: "3306"
  DB_HOST: "marmelade-preprod.cismxf0nbec3.eu-west-3.rds.amazonaws.com"

  LIGHTHOUSE_DOMAIN: "gql.preprod.mrmld.net"
  LIGHTHOUSE_URI: "/"

  AWS_DEFAULT_REGION: "eu-west-3"
  AWS_SES_DEFAULT_REGION: "eu-west-1"
  AWS_BUCKET: "images.preprod.mrmld.net"
  IMAGES_URL: "https://images.preprod.mrmld.net/"

  CASHIER_MODEL: "App\\Group"
  CASHIER_CURRENCY: "eur"
  CASHIER_CURRENCY_LOCALE: "fr_FR"
