apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: preprod
  labels:
    app: backend
  name: backend-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: 889957192357.dkr.ecr.eu-west-3.amazonaws.com/marmelade-backend:latest
              name: cron
              command: ["php", "artisan", "schedule:run"]
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: backend-config
                - secretRef:
                    name: backend-secret
          restartPolicy: OnFailure