apiVersion: v1
kind: Service
metadata:
  namespace: preprod
  labels:
    app: backend
  name: backend-service

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: 	arn:aws:acm:eu-west-3:889957192357:certificate/50e8aa4b-4430-4761-8ead-f6bf7b0f6e22
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"

spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 80
  type: LoadBalancer