import { createActions } from 'redux-actions';

const {
  getAuthors,
  getAuthorsFailed,
  getAuthorsSucceed,
  addAuthor,
  addAuthorFailed,
  addAuthorSucceed,
  editAuthor,
  editAuthorFailed,
  editAuthorSucceed,
  createAuthor,
  createAuthorFailed,
  createAuthorSucceed,
  updateAuthor,
  updateAuthorFailed,
  updateAuthorSucceed,
  showAuthor,
  showAuthorFailed,
  showAuthorSucceed,
} = createActions({
  GET_AUTHORS: (params) => ({params}),
  GET_AUTHORS_FAILED: error => ({ error }),
  GET_AUTHORS_SUCCEED: authors => ({ authors }),
  ADD_AUTHOR: (params) => ({params}),
  ADD_AUTHOR_FAILED: error => ({ error }),
  ADD_AUTHOR_SUCCEED: author => ({ author }),
  EDIT_AUTHOR: (id) => ({id}),
  EDIT_AUTHOR_FAILED: error => ({ error }),
  EDIT_AUTHOR_SUCCEED: author => ({ author }),
  CREATE_AUTHOR: () => ({}),
  CREATE_AUTHOR_FAILED: error => ({ error }),
  CREATE_AUTHOR_SUCCEED: author => ({ author }),
  UPDATE_AUTHOR: (id, params) => ({id: id, params: params}),
  UPDATE_AUTHOR_FAILED: error => ({ error }),
  UPDATE_AUTHOR_SUCCEED: id => ({ id }),
  SHOW_AUTHOR: (id) => ({id}),
  SHOW_AUTHOR_FAILED: error => ({ error }),
  SHOW_AUTHOR_SUCCEED: author => ({ author }),
});

export {
  getAuthors,
  getAuthorsFailed,
  getAuthorsSucceed,
  addAuthor,
  addAuthorFailed,
  addAuthorSucceed,
  editAuthor,
  editAuthorFailed,
  editAuthorSucceed,
  createAuthor,
  createAuthorFailed,
  createAuthorSucceed,
  updateAuthor,
  updateAuthorFailed,
  updateAuthorSucceed,
  showAuthor,
  showAuthorFailed,
  showAuthorSucceed,
};
