import { createActions } from 'redux-actions';

const {
  getShopTrainings,
  getShopTrainingsFailed,
  getShopTrainingsSucceed,
  addShopTraining,
  addShopTrainingFailed,
  addShopTrainingSucceed,
  editShopTraining,
  editShopTrainingFailed,
  editShopTrainingSucceed,
  createShopTraining,
  createShopTrainingFailed,
  createShopTrainingSucceed,
  updateShopTraining,
  updateShopTrainingFailed,
  updateShopTrainingSucceed,
  deleteShopTraining,
  deleteShopTrainingSucceed,
  deleteShopTrainingFailed,
} = createActions({
  GET_SHOP_TRAININGS: (params) => ({params}),
  GET_SHOP_TRAININGS_FAILED: error => ({ error }),
  GET_SHOP_TRAININGS_SUCCEED: shopTrainings => ({ shopTrainings }),
  ADD_SHOP_TRAINING: (params) => ({params}),
  ADD_SHOP_TRAINING_FAILED: error => ({ error }),
  ADD_SHOP_TRAINING_SUCCEED: shopTraining => ({ shopTraining }),
  EDIT_SHOP_TRAINING: (id) => ({id}),
  EDIT_SHOP_TRAINING_FAILED: error => ({ error }),
  EDIT_SHOP_TRAINING_SUCCEED: shopTraining => ({ shopTraining }),
  CREATE_SHOP_TRAINING: () => ({}),
  CREATE_SHOP_TRAINING_FAILED: error => ({ error }),
  CREATE_SHOP_TRAINING_SUCCEED: shopTraining => ({ shopTraining }),
  UPDATE_SHOP_TRAINING: (id, params) => ({id: id, params: params}),
  UPDATE_SHOP_TRAINING_FAILED: error => ({ error }),
  UPDATE_SHOP_TRAINING_SUCCEED: id => ({ id }),
  DELETE_SHOP_TRAINING: (id) => ({id}),
  DELETE_SHOP_TRAINING_SUCCEED: (id) => ({id}),
  DELETE_SHOP_TRAINING_FAILED: (error) => ({error}),
});

export {
  getShopTrainings,
  getShopTrainingsFailed,
  getShopTrainingsSucceed,
  addShopTraining,
  addShopTrainingFailed,
  addShopTrainingSucceed,
  editShopTraining,
  editShopTrainingFailed,
  editShopTrainingSucceed,
  createShopTraining,
  createShopTrainingFailed,
  createShopTrainingSucceed,
  updateShopTraining,
  updateShopTrainingFailed,
  updateShopTrainingSucceed,
  deleteShopTraining,
  deleteShopTrainingSucceed,
  deleteShopTrainingFailed,
};
