import { createActions } from 'redux-actions';

const {
  getQuizzes,
  getQuizzesFailed,
  getQuizzesSucceed,
  createQuizz,
  createQuizzFailed,
  createQuizzSucceed,
  addQuizz,
  addQuizzFailed,
  addQuizzSucceed,
  showQuizz,
  showQuizzFailed,
  showQuizzSucceed,
  editQuizz,
  editQuizzFailed,
  editQuizzSucceed,
  updateQuizz,
  updateQuizzFailed,
  updateQuizzSucceed,
  updateImage,
  updateImageFailed,
  updateImageSucceed,
  
} = createActions({
  GET_QUIZZES: (params) => ({params}),
  GET_QUIZZES_FAILED: error => ({ error }),
  GET_QUIZZES_SUCCEED: quizzes => ({ quizzes }),
  CREATE_QUIZZ: () => ({}),
  CREATE_QUIZZ_FAILED: error => ({ error }),
  CREATE_QUIZZ_SUCCEED: quizz => ({ quizz }),
  ADD_QUIZZ: (params) => ({params}),
  ADD_QUIZZ_FAILED: error => ({ error }),
  ADD_QUIZZ_SUCCEED: quizz => ({ quizz }),
  SHOW_QUIZZ: (id) => ({id}),
  SHOW_QUIZZ_FAILED: error => ({ error }),
  SHOW_QUIZZ_SUCCEED: quizz => ({ quizz }),
  EDIT_QUIZZ: (id) => ({id}),
  EDIT_QUIZZ_FAILED: error => ({ error }),
  EDIT_QUIZZ_SUCCEED: quizz => ({ quizz }),
  UPDATE_QUIZZ: (id, params) => ({id: id, params: params}),
  UPDATE_QUIZZ_FAILED: error => ({ error }),
  UPDATE_QUIZZ_SUCCEED: quizz => ({ quizz }),
  UPDATE_IMAGE: (id, params) => ({id: id, params: params}),
  UPDATE_IMAGE_FAILED: error => ({ error }),
  UPDATE_IMAGE_SUCCEED: status => ({ status }),
});

export {
  getQuizzes,
  getQuizzesFailed,
  getQuizzesSucceed,
  createQuizz,
  createQuizzFailed,
  createQuizzSucceed,
  addQuizz,
  addQuizzFailed,
  addQuizzSucceed,
  showQuizz,
  showQuizzFailed,
  showQuizzSucceed,
  editQuizz,
  editQuizzFailed,
  editQuizzSucceed,
  updateQuizz,
  updateQuizzFailed,
  updateQuizzSucceed,
  updateImage,
  updateImageFailed,
  updateImageSucceed
};
